### ISSUE TITLE
Handle de Queries 

### ISSUE THREAD

**Issue by Sofka-XT** [Sofka-XT/ddd-java-demo#4]
Subcriptor para los eventos de los casos de uso.

- Mapear los eventos y pasarlo a un Normalizador para guardar el evento en una estructura de datos.
- El normalizador puede estar subcrito a varios eventos. 
- El normalizador usar el repositorio para guardar en una base de datos SQL (es una base de datos en memoria para el demo)

https://docs.microsoft.com/en-us/azure/architecture/patterns/materialized-view

**Comment by LisbeyUrrea** [comment]
done.
