### ISSUE TITLE
Comando Asyn (API)

### ISSUE THREAD

**Issue by Sofka-XT** [Sofka-XT/ddd-java-demo#6]
Hacer la API donde puedan recibir un POST con el comando especifico.

- Usar el RestController para ejecutar el comando, pero se debe ejeuctar el caso de uso de forma asincrona. 
- La respuesta del comando debe ser de inmediato arrojando un 200 como respuesta HTTP
- De existir una factory/builder para asociar el caso de uso con el comando.

**Comment by LisbeyUrrea** [comment]
Issue Ready!
